train_list: ['040', '041', '089', '029', '066', '043', '139', '106', 
             '057', '115', '158', '044', '119', '109', '013', '117', 
             '039', '073', '056', '084', '077', '005', '046', '123', 
             '088', '021', '042', '124', '052', '015', '028', '069', 
             '105', '019', '067', '016', '001', '023', '095', '024', 
             '072', '113', '058', '030', '027', '032', '065', '011', 
             '097', '064', '078', '080', '070', '112', '003', '120', 
             '098', '101', '054', '002', '017', '090', '071', '116', 
             '037', '034', '149', '110', '053']

val_list: ['094', '103', '102', '122', '033', '038', '035']

pandaset_dir: '/share/qi.chao/open_sor_data/pandaset/pandaset_0'

seg_grabcut_dir: '/share/qi.chao/open_sor_data/pandaset/seed_jpg/grabcut'

seg_seed_lidar_dir: '/share/qi.chao/open_sor_data/pandaset/seed_jpg/lidar'

labels:
  {1: 'Smoke', 2: 'Exhaust', 3: 'Spray or rain', 4: "Reflection", 5: 'Vegetation', 6: 'Ground', 7: 'Road',
   8: 'Lane Line Marking', 9: 'Stop Line Marking', 10: 'Other Road Marking', 11: 'Sidewalk', 12: 'Driveway', 
   13: 'Car', 14: 'Pickup Truck', 15: 'Medium-sized Truck', 16: 'Semi-truck', 17: 'Towed Object', 18: 'Motorcycle',
   19: 'Other Vehicle - Construction Vehicle', 20: 'Other Vehicle - Uncommon', 21: 'Other Vehicle - Pedicab',
   22: 'Emergency Vehicle', 23: 'Bus', 24: 'Personal Mobility Device', 25: 'Motorized Scooter', 26: 'Bicycle',
   27: 'Train', 28: 'Trolley', 29: 'Tram / Subway', 30: 'Pedestrian', 31: 'Pedestrian with Object', 32: 'Animals - Bird', 
   33: 'Animals - Other', 34: 'Pylons', 35: 'Road Barriers', 36: 'Signs', 37: 'Cones', 38: 'Construction Signs',
   39: 'Temporary Construction Barriers', 40: 'Rolling Containers', 41: 'Building', 42: 'Other Static Object'}

labels_seg:
  {1: 'Vegetation', 3: 'Road', 4: 'road_mark', 5: 'Sidewalk', 6: 'warning_pole', 7: 'car',
   8: pickup_truck, 9: 'truck', 10: 'Motorcycle', 11: 'Pedicab', 12: 'rolling_Containers', 13: 'bus', 14: 'Bicycle',
   16: 'Pedestrian', 17: 'animal', 18: 'Barriers', 19: 'Signs', 20: 'cone', 21: 'building'}
  
learning_map:
  {1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 4, 10: 4, 11: 5, 12: 0, 13: 7, 14: 8, 15: 9, 16: 0, 17: 0,
   18: 10, 19: 0, 20: 0, 21: 11, 22: 0, 23: 13, 24: 0, 25: 10, 26: 14, 27: 0, 28: 15, 29: 0, 30: 16, 31: 16, 
   32: 17, 33: 17, 34: 6, 35: 18, 36: 19, 37: 20, 38: 0, 39: 0, 40: 12, 41: 21, 42: 0}

seg_paste: [1, 8, 9, 10, 11, 12, 13, 14, 16, 18, 20]

paste2label: 
  {1: [6, 11], 8: [7, 8, 9, 10], 9: [7, 8, 9, 10], 10: [7, 8, 9, 10, 11], 11: [7, 8, 9, 10, 11], 
   12: [11], 13: [7, 8, 9, 10], 14: [6, 7, 8, 9, 10, 11], 16: [7, 8, 9, 10], 18: [7], 20: [6, 11]}